# Generated by Django 5.2.4 on 2025-08-01 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheticEventTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Synthetic Event Targets',
            },
        ),
        migrations.CreateModel(
            name='SyntheticEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Synthetic Event Types',
            },
        ),
        migrations.CreateModel(
            name='SyntheticEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synthetic_events', to='technical_information.syntheticeventtarget')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synthetic_events', to='technical_information.syntheticeventtype')),
            ],
            options={
                'verbose_name_plural': 'Synthetic Events',
            },
        ),
    ]
