# Generated by Django 5.2.4 on 2025-07-31 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolcategory',
            name='description',
        ),
    ]
